using System.Net;
using System.Net.Mail;
using Erpos.Application.Common;
using Erpos.Domain.Entities;
using Microsoft.Extensions.Configuration;

namespace Erpos.Infrastructure.Platform;

/// <summary>Files on local disk (a Docker volume in production) under Storage:Path.</summary>
public class LocalFileStorage(string root) : IFileStorage
{
    private readonly string _root = Path.GetFullPath(root);

    private string PathFor(string key)
    {
        var full = Path.GetFullPath(Path.Combine(_root, key.Replace('/', Path.DirectorySeparatorChar)));
        // Keys are generated by the application, but never let one escape the storage folder.
        if (!full.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.Ordinal)) throw new InvalidOperationException("Invalid storage key.");
        return full;
    }

    public async Task SaveAsync(string key, Stream content, CancellationToken ct)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true);
        await content.CopyToAsync(file, ct);
    }

    public Task<Stream> OpenAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (!File.Exists(path)) throw new NotFoundException("File");
        return Task.FromResult<Stream>(new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true));
    }

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (File.Exists(path)) File.Delete(path);
        return Task.CompletedTask;
    }
}

/// <summary>
/// Email delivery: SMTP when Email:Smtp:Host is set; otherwise .eml files in Email:PickupDirectory (development);
/// otherwise disabled (messages wait in the outbox until a server is configured).
/// </summary>
public class SmtpEmailTransport(IConfiguration config) : IEmailTransport
{
    private string? Host => config["Email:Smtp:Host"];
    private string? Pickup => config["Email:PickupDirectory"];
    public string Mode => !string.IsNullOrWhiteSpace(Host) ? "smtp" : !string.IsNullOrWhiteSpace(Pickup) ? "pickup" : "disabled";

    public async Task SendAsync(OutboxEmail message, CancellationToken ct)
    {
        using var mail = new MailMessage(config["Email:From"] ?? "ERPOS <no-reply@erpos.local>", message.To, message.Subject, message.HtmlBody) { IsBodyHtml = true };
        using var client = new SmtpClient();
        if (Mode == "smtp")
        {
            client.Host = Host!;
            client.Port = config.GetValue("Email:Smtp:Port", 587);
            client.EnableSsl = config.GetValue("Email:Smtp:EnableSsl", true);
            if (!string.IsNullOrWhiteSpace(config["Email:Smtp:User"]))
                client.Credentials = new NetworkCredential(config["Email:Smtp:User"], config["Email:Smtp:Password"]);
        }
        else if (Mode == "pickup")
        {
            Directory.CreateDirectory(Pickup!);
            client.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
            client.PickupDirectoryLocation = Path.GetFullPath(Pickup!);
        }
        else throw new InvalidOperationException("Email is not configured.");
        await client.SendMailAsync(mail, ct);
    }
}
